<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Enrollment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get enrollment by id
     */
    function get_enrollment($id)
    {
        return $this->db->get_where('enrollments',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all enrollments
     */
    function get_all_enrollments()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('enrollments')->result_array();
    }
        
    /*
     * function to add new enrollment
     */
    function add_enrollment($params)
    {
        $this->db->insert('enrollments',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update enrollment
     */
    function update_enrollment($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('enrollments',$params);
    }
    
    /*
     * function to delete enrollment
     */
    function delete_enrollment($id)
    {
        return $this->db->delete('enrollments',array('id'=>$id));
    }
}
